sudo: required
addons:
  chrome: stable
  sonarcloud:
    organization: dcousino-github
    token:
      secure: uNGq5GyDJSW35ioIyYTcM2G9/JH6tHUJCwNNo5cryf/6R7aUu5h7LuBD9Oqgsoll3xxeq1Nb+64tpFbsVP2Jbhaf7KIYa7mkxWafgxTsVQlv+Mkx5kDzLQelq57cGvZ5wyjiLM/FNVAV/eNSQ+aPJgDQw1Ypgm0/6Q5rldcXGaFoA1ZfH32dMbpZA9zaBHK+rfowg9Ip21s4SkStEFcXI+9iosUDsRdB8LA3JQaZXInI5SUV87EUUG4NpoeSVR5kc4oJ/1KFYmpd8WMA1dCnjyIG+FcYk576WODxoAoW+SOzIZXV6cMvXEuhtL3vdLsnNy7dJ7lN2AxciqYK67hQq6VBGleIfx9LlVJdhOdHoRUx+eyyEwrxqC2GrFXpgaoxTO6VEI9gRwajvHET0nZX/GBN9ST5kBrFo5VAhFi0334+G3sTalw9HN8fNLZhSurKYKY8eqMOWhdD/KvHqwUgLRvM/cHcxoeLAPSOAMOLkYNBkz3K4/M8Pwszuv9Exo0wnXWWsmqs3h2P1hTta3UaP9m8RrA9Ri2FMjGNb8T8wpQEJOEwm7DdoW6YjrJ0HDzfaiynOYfUCt2Q8MCMue5AfQLmYDG3nKyzONt9QA2v+tVaUutD+KX0DL0bwh1AQjPI6k3JizCcAarT8UsWUZzjhO1SruqXYVMrrB8XCHkmlIg=
language: node_js
node_js:
  - '8'
branches:
  only:
    - master
before_script:
  - sonar-scanner
  - cd client && npm install -g @angular/cli && npm install --save-dev @angular-devkit/build-angular
script:
  - ng build --prod --aot
  - ng test
deploy:
  provider: s3
  access_key_id:
    secure: w3eIzTuPJGSixJY0aCcXr89IXJe6AJsNAI6rGqZNWsIdiXiqZLNG1m5LmthlBN7K/LWgH9yDUvKDKuzfsnGy0wcjNxyCkNCDAyqpykbpYqT6EtqJovK5KmJB1kavkM40Fyf8fz/d7TAEMVMNJKfQ8/j+J3rswoV/mgAPn0TPfMEY/kn4fphUCwebaDNUeMMmYAQ2sUE9aqtjvGoN3oQwX8KW+UJPhEJq1gv9efYx7G5kQ7Sa8LjPoiXKYngCIr4Wt+Zz8vOuAD/eE/XEcPTaf+p52lNEMq5qyILWQvgf76P7Nm4Gcey2xpQHo4u/EmRJ1CGLoLlLFJmkuAF1IWoP0L3nid7UGp2oxr5tcZEUABLextE031oPLAPCEfJRkwMknB2/5BtiA7hC+uZi2pHADbe9nf/Fv3q55axkIo1XVny3CS9TEGAoJxVbWdi7ALLQCkA0d0ndFTadCjEKF7fnvLjKBjcWBCyN9kf14ZlV1eiPIZBH+85h4LXq54Gnx6gnTt3basxC9Z9E2t3clM1zUQk/anknoPbol0PpPBqdgyuxTIrvFMqXouWmS+oR2D6sNLs6z4g7mE/WXJGf6OIEQLzcnbRxgBTu4ReTtrLgCkSVkrMFWFNNeVgvuEJoZSR2CWoK9z528q7a5gJSJzu0f3sw2ttjBAVScA22bS1vOcE=
  secret_access_key:
    secure: XQ5uCwLxQmrv+ewm0q7TDlhH29wDpr4gRJf17PmsEGcPEm38sf4XzjqnACR5HNvnvrc/KVvRzs/yGVfjJIN77Hgml3r5Maqo0bcwkimI3eOmJFtGr0/Iz613ICmgfcCU7dKebC4KciISOkGDIlnIx/eFrmY8ag9tnMrYbkXWrZD1+MvTWSC2QdknvdUcktyFCBtjpNF7HCcItHL8wJtveyQOePceMqyT+kXl1jnV0x16zCqt0sn2kywLPgCyixw9ZvZa/7V3YoHG06tQCBrNFePXs/yRA3dC+ScgME9QcA9ywLSbiRRufXAWN/kLmpgsRNUHjp9QSc5WGbKVoxx1HNXt6VTLM+nhliQmzCs9QIcQJiccX5kRkHA0TslTYeF5Frcp55kgy2YxCFzsF8blgOjRTJmRmwUwAXY6s8qkLOUn6Uu6NGlj/6U9D2RPiiylo8TJhYVN5Ri3LS9WwZA0xJ+tGcuuhIeSh+0lTGMOq22d5CtWrpE8jAhNzhGyGNbY9MQHO5FCfK3id3BrcTh1jMSvceletGaGu3C5TnpsDLoEPEHpM+bGuL5N6MhDVDqRux+dqMqcmX6EGr2dWXt+8qBPoip0Wftrt3U3GqcwUzG42vLnb81gUy4B8dGkc2gYrIt319S/TNHnTdV3eOU/VeB44OnRp2NKupmNqBV44vA=
  bucket: walcart
  skip_cleanup: true
  acl: public_read
