sudo: required
addons:
  chrome: stable
  sonarcloud:
    organization: 'dcousino-github'
    token:
      secure: 'uNGq5GyDJSW35ioIyYTcM2G9/JH6tHUJCwNNo5cryf/6R7aUu5h7LuBD9Oqgsoll3xxeq1Nb+64tpFbsVP2Jbhaf7KIYa7mkxWafgxTsVQlv+Mkx5kDzLQelq57cGvZ5wyjiLM/FNVAV/eNSQ+aPJgDQw1Ypgm0/6Q5rldcXGaFoA1ZfH32dMbpZA9zaBHK+rfowg9Ip21s4SkStEFcXI+9iosUDsRdB8LA3JQaZXInI5SUV87EUUG4NpoeSVR5kc4oJ/1KFYmpd8WMA1dCnjyIG+FcYk576WODxoAoW+SOzIZXV6cMvXEuhtL3vdLsnNy7dJ7lN2AxciqYK67hQq6VBGleIfx9LlVJdhOdHoRUx+eyyEwrxqC2GrFXpgaoxTO6VEI9gRwajvHET0nZX/GBN9ST5kBrFo5VAhFi0334+G3sTalw9HN8fNLZhSurKYKY8eqMOWhdD/KvHqwUgLRvM/cHcxoeLAPSOAMOLkYNBkz3K4/M8Pwszuv9Exo0wnXWWsmqs3h2P1hTta3UaP9m8RrA9Ri2FMjGNb8T8wpQEJOEwm7DdoW6YjrJ0HDzfaiynOYfUCt2Q8MCMue5AfQLmYDG3nKyzONt9QA2v+tVaUutD+KX0DL0bwh1AQjPI6k3JizCcAarT8UsWUZzjhO1SruqXYVMrrB8XCHkmlIg='
language: node_js
node_js:
  - '8'

branches:
  only:
    - master

before_script:
  - sonar-scanner
  - cd client && npm install -g @angular/cli && npm install --save-dev @angular-devkit/build-angular

script:
  - ng build --prod --aot
  - ng test
