sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - '8'

branches:
  only:
    - master

before_script:
  - cd client && npm install -g @angular/cli && npm install --save-dev @angular-devkit/build-angular

script:
  - ng build --prod --aot
  - ng test
